apiVersion: apps/v1
kind: Deployment
metadata:
  name: sole-spot-deployment
  labels:
    app: sole-spot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sole-spot
  template:
    metadata:
      labels:
        app: sole-spot
    spec:
      containers:
        - name: sole-spot-container
          image: sudhin123/sole-spot:latest
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "postgres"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbuser
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbpassword
            - name: DBNAME
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbname
            - name: DBPORT
              value: "5432"
