name: The-Sole-Spot CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Setup SSH Key
      - name: Setup SSH Key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

      # Step 2: Deploy to EC2
      - name: Build and Replace Binary on EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$PUBLIC_IP << 'EOF'
            # Pull latest code
            cd ~/The-Sole-Spot
            git pull origin main

            # Build Go binary
            go mod tidy
            go build -o solespot ./cmd1/main.go

            # Replace binary
            sudo mv solespot /usr/bin/solespot
            sudo chmod +x /usr/bin/solespot

            # Restart service
            sudo systemctl restart solespot.service
            sudo systemctl status solespot.service
          EOF

      # Step 3: Cleanup SSH Key
      - name: Cleanup
        run: rm -f key.pem
