name: The-Sole-Spot CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Adjust if you're using a different version

      # Step 3: Download Dependencies
      - name: Download Go Modules
        run: go mod tidy

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: go test -v ./...

      # Step 5: Setup SSH Key
      - name: Setup SSH Key
        if: success()
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

      # Step 6: Deploy to EC2
      - name: Build and Replace Binary on EC2
        if: success()
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$PUBLIC_IP << 'EOF'
            cd ~/The-Sole-Spot
            git pull origin main

            go mod tidy
            go build -o solespot ./cmd1/main.go

            sudo mv solespot /usr/bin/solespot
            sudo chmod +x /usr/bin/solespot

            sudo systemctl restart solespot.service
            sudo systemctl status solespot.service
          EOF

      # Step 7: Cleanup SSH Key
      - name: Cleanup
        run: rm -f key.pem
