name: The-Sole-Spot CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' 

      - name: Download Go Modules
        run: go mod tidy

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Setup SSH Key
        if: success()
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

      - name: Build and Replace Binary on EC2
        if: success()
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$PUBLIC_IP << 'EOF'
            cd ~/The-Sole-Spot
            git pull origin main

            go mod tidy
            go build -o solespot ./cmd1/main.go

            sudo mv solespot /usr/bin/solespot
            sudo chmod +x /usr/bin/solespot

            sudo systemctl restart solespot.service
            sudo systemctl status solespot.service
          EOF

      - name: Cleanup
        run: rm -f key.pem
